# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'


- task: AzureImageBuilderTask@1
  inputs:
    imageSource: 'marketplace'
    baseImage: 'MicrosoftWindowsDesktop:Windows-10:19h1-evd:windows'
    provisioner: 'powershell'
    windowsUpdateProvisioner: true
    packagePath: 'https://raw.githubusercontent.com/potty91/AIB/master/buildArtifacts'
    storageAccountName: 'vseinfraimages'
    distributeType: 'sig'
    galleryImageId: '/subscriptions/43559797-46d3-45a2-bc18-d03ced80f12b/resourceGroups/VSE_WVD_Images2/providers/Microsoft.Compute/galleries/myaibwvdsig01/images/winWVDimages'
    replicationRegions: 'Eastus2,Eastus'
    ibSubscription: 'Visual Studio Enterprise(43559797-46d3-45a2-bc18-d03ced80f12b)'
    ibAzureResourceGroup: 'VSE_WVD_Pooled_3'
    ibLocation: 'westus'