steps:
- task: AzureImageBuilder.devOps-task-for-azure-image-builder.custom-build-release-task.AzureImageBuilderTask@1
  displayName: 'Azure VM Image Builder Task'
  inputs:
    managedIdentity: '/subscriptions/43559797-46d3-45a2-bc18-d03ced80f12b/resourceGroups/VSE_WVD_Images/providers/Microsoft.ManagedIdentity/userAssignedIdentities/AIBuilderTemp'
    imageSource: marketplace
    baseImage: 'MicrosoftWindowsDesktop:Windows-10:19h1-evd'
    provisioner: powershell
    windowsUpdateProvisioner: true
    distributeType: sig
    galleryImageId: '/subscriptions/43559797-46d3-45a2-bc18-d03ced80f12b/resourceGroups/VSE_WVD_Images/providers/Microsoft.Compute/galleries/myaibsig01/images/winSvrimages'
    replicationRegions: 'eastus2,northeurope'
    ibSubscription: 'Visual Studio Enterprise(43559797-46d3-45a2-bc18-d03ced80f12b)'
    ibAzureResourceGroup: 'VSE_WVD_Images'
    ibLocation: eastus2